### ISSUE TITLE
java.io.IOException: Failed to initialize All-Projects refs

### ISSUE THREAD

**Issue by lgd8069465** [GerritCodeReview/gerrit#4]
```
[root@zabbixclient opt]# java -jar gerrit*.war init --batch --dev -d ~/gerrit_testsite
Generating SSH host key ... ed25519...unknown key type ed25519
 done
Exception in thread "main" com.google.gwtorm.server.OrmException: Cannot initialize schema
	at com.google.gerrit.server.schema.SchemaUpdater.update(SchemaUpdater.java:113)
	at com.google.gerrit.pgm.init.BaseInit$SiteRun.upgradeSchema(BaseInit.java:389)
	at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:146)
	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:223)
	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:119)
	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:63)
	at Main.main(Main.java:24)
Caused by: java.io.IOException: Failed to initialize All-Projects refs:
PackedBatchRefUpdate[
  CREATE: 0000000000000000000000000000000000000000 67249510f0db8e050adbbf9301021c5103125dff refs/meta/config  (LOCK_FAILURE)
]
	at com.google.gerrit.server.schema.AllProjectsCreator.execute(AllProjectsCreator.java:241)
	at com.google.gerrit.server.schema.AllProjectsCreator.initAllProjects(AllProjectsCreator.java:203)
	at com.google.gerrit.server.schema.AllProjectsCreator.create(AllProjectsCreator.java:120)
	at com.google.gerrit.server.schema.SchemaCreator.create(SchemaCreator.java:96)
	at com.google.gerrit.server.schema.SchemaUpdater.update(SchemaUpdater.java:111)
	... 11 more
[root@zabbixclient opt]# 

```
Why?

**Comment by lgd8069465** [comment]
![123](https://user-images.githubusercontent.com/7867042/38802082-1e5a11f2-419e-11e8-83e8-94631c7ab1bf.png)

**Comment by lgd8069465** [comment]
Create a "gerrit_testsite/git/All-Projects.git/refs/meta/config" file with value "67249510f0db8e050adbbf9301021c5103125dff".
The value is from "67249510f0db8e050adbbf9301021c5103125dff refs/meta/config  (LOCK_FAILURE)".
I do not Why?
